In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from source.utility import list_all_files

pd.set_option('max_columns', 200)

# Cities responses

In [4]:
city_ddict = pd.read_csv('data/raw/Cities/Cities Responses/Full_Cities_Response_Data_Dictionary.csv')

city_ddict.head()

,field,description,column _entries,example
0,Questionnaire,Questionnaire and questionnaire year the compa...,Cities 2020,NaN
1,Year Reported to CDP,Cities Disclosure cycle survey year.,2020,NaN
2,Account Number,The unique identifier given to every city orga...,35883,NaN
3,Organization,Name of the City organisation disclosing,City of San Jose,NaN
4,Country,Country of city,United States of America,NaN

In [6]:
city_ddict

,field,description,column _entries,example
0,Questionnaire,Questionnaire and questionnaire year the compa...,Cities 2020,NaN
1,Year Reported to CDP,Cities Disclosure cycle survey year.,2020,NaN
2,Account Number,The unique identifier given to every city orga...,35883,NaN
3,Organization,Name of the City organisation disclosing,City of San Jose,NaN
4,Country,Country of city,United States of America,NaN
5,CDP Region,CDP operation region City is located within,North America,NaN
6,Parent Section,Module ('Parent Section') of the CDP questionn...,Emissions Reduction,NaN
7,Section,Section of the CDP questionnaire the question ...,Mitigation Actions,NaN
8,Question Number,Question number of response,5.4,NaN
9,Question Name,Question name,Describe the anticipated outcomes of the most ...,NaN
10,Column Number,Column number of matrix set (Table) or matrix ...,9,NaN
11,Column Name,Column name of matrix set (Table) or matrix dy...,Co-benefit area,NaN
12,Row Number,Row number of matrix set (Table) or matrix dyn...,6,NaN
13,Row Name,Row name of matrix set (Table) or matrix dynam...,Population that is food insecure),NaN
14,Response Answer,Question response submitted by company,Greening the economy,"Can range from string, integar and double data..."
15,Comments,Added response clarifications from Company or ...,"Current population: 165,571Current population ...",NaN
16,File Name,File name of any supporting material attached ...,(4.13)2017GHG_GPC_1080620.xlsx,NaN
17,Last update,Last update of response,09/07/2020 09:45,NaN

In [7]:
city_2018 = pd.read_csv('data/raw/Cities/Cities Responses/2018_Full_Cities_Dataset.csv')

city_2018.head()

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update
0,CDP Cities 2018,2018,3203,City of Chicago,United States of America,North America,Water,Wastewater,16.1,Please provide the percentage breakdown of the...,1,Percentage of wastewater collected,5,Other type of wastewater,NaN,NaN,NaN,24/06/2020 05:28:18 AM
1,CDP Cities 2018,2018,50555,City of Hamilton,Canada,North America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,5,Probability of hazard,4,NaN,Medium High,NaN,NaN,24/06/2020 05:28:18 AM
2,CDP Cities 2018,2018,50392,Prefeitura de Vitória,Brazil,Latin America,Emissions Reduction: City-wide,Emissions Reduction Actions : City-wide,8.4,What actions is your city taking to reduce emi...,1,Emissions reduction project activity,3,NaN,On-site renewable energy generation,NaN,NaN,24/06/2020 05:28:18 AM
3,CDP Cities 2018,2018,36522,Comune di Verbania,Italy,Europe,Strategy,Energy,9.0,Please indicate the energy mix of electricity ...,2,Gas,1,Energy consumption percentage,NaN,NaN,NaN,24/06/2020 05:28:18 AM
4,CDP Cities 2018,2018,35873,Municipality of Medellín,Colombia,Latin America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,3,Magnitude of impact,6,NaN,Serious,NaN,NaN,24/06/2020 05:28:18 AM

In [11]:
city_2019 = pd.read_csv('data/raw/Cities/Cities Responses/2019_Full_Cities_Dataset.csv')

city_2019.head()

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update
0,Cities 2019,2019,54113,City of Flagstaff,United States of America,North America,NaN,Energy,8.0a,Please provide details of your renewable energ...,2,Energy / electricity types covered by target,3,NaN,Other: Proportion of community electricity use...,NaN,NaN,24/06/2020 05:30:36 AM
1,Cities 2019,2019,35894,Ville de Montreal,Canada,North America,Emissions Reduction,Mitigation Actions,5.4,Describe the anticipated outcomes of the most ...,9,Co-benefit area,1,NaN,NaN,source: http://ville.montreal.qc.ca/pls/portal...,NaN,24/06/2020 05:30:36 AM
2,Cities 2019,2019,44185,Suwon City,Republic of Korea,East Asia,Emissions Reduction,Mitigation Target setting,5.0a,Please provide details of your total city-wide...,3,Boundary of target relative to city boundary (...,1,NaN,Same – covers entire city and nothing else,NaN,NaN,24/06/2020 05:30:36 AM
3,Cities 2019,2019,59165,Gladsaxe Kommune,Denmark,Europe,NaN,Transport,10.1,What is the mode share of each transport mode ...,7,Taxis or For Hire Vehicles,1,Please complete,3,NaN,NaN,24/06/2020 05:30:36 AM
4,Cities 2019,2019,36263,Comune di Ravenna,Italy,Europe,Water Security,Water Supply Management,14.4,Please select the actions you are taking to re...,2,Adaptation action,1,NaN,Water use restrictions,NaN,NaN,24/06/2020 05:30:36 AM

# Cities disclosing

In [12]:
list_all_files(location='data/', pattern='Cities Disclosing')

['data/raw/Cities/Cities Disclosing/Cities_Disclosing_to_CDP_Data_Dictionary.csv',
 'data/raw/Cities/Cities Disclosing/2018_Cities_Disclosing_to_CDP.csv',
 'data/raw/Cities/Cities Disclosing/2019_Cities_Disclosing_to_CDP.csv',
 'data/raw/Cities/Cities Disclosing/2020_Cities_Disclosing_to_CDP.csv']

In [13]:
cities_ddict = pd.read_csv('data/raw/Cities/Cities Disclosing/Cities_Disclosing_to_CDP_Data_Dictionary.csv')
cities_ddict.head()

,field,description,column _entries,example
0,Year Reported to CDP,Cities Disclosure cycle survey year.,2020,NaN
1,Account Number,The unique identifier given to every city orga...,49335,NaN
2,Organization,Name of the City organisation disclosing,Metropolitan Government of Nashville and David...,NaN
3,City,Name of the City the city organisation is disc...,Nashville,NaN
4,Country,Country of city,United States of America,NaN

In [14]:
cities_2018 = pd.read_csv('data/raw/Cities/Cities Disclosing/2018_Cities_Disclosing_to_CDP.csv')

cities_2018.head()

,Year Reported to CDP,Account Number,Organization,City,Country,CDP Region,Reporting Authority,Access,First Time Discloser,Population,Population Year,City Location,Last update
0,2018,58671,Helsingør Kommune / Elsinore Municipality,Helsingør,Denmark,Europe,CDP Cities,public,No,62686.0,2017,POINT (12.5921 56.0308),2020-06-25T04:52:49.050
1,2018,59167,Municipalidad de Providencia,Providencia,Chile,Latin America,CDP Cities,public,No,126487.0,2012,POINT (-70.6092 -33.4313),2020-06-25T04:52:49.050
2,2018,50553,City of Fresno,Fresno,United States of America,North America,CDP Cities,public,Yes,527438.0,2017,POINT (-119.773 36.7468),2020-06-25T04:52:49.050
3,2018,826407,Munícipio de Mirandela,Mirandela,Portugal,Europe,CDP Cities,public,Yes,11852.0,2011,POINT (-7.1753 41.51),2020-06-25T04:52:49.050
4,2018,60375,Gobiernación del Archipiélago de San Andrés,Archipiélago de San Andrés,Colombia,Latin America,CDP Cities,public,No,120000.0,2017,POINT (-81.6976 12.5794),2020-06-25T04:52:49.050

# Corporations disclosing

In [15]:
list_all_files(location='data/', pattern='Corporations Disclosing')

['data/raw/Corporations/Corporations Disclosing/Climate Change/Corporations_Disclosing_to_CDP_Data_Dictionary.csv',
 'data/raw/Corporations/Corporations Disclosing/Climate Change/2018_Corporates_Disclosing_to_CDP_Climate_Change.csv',
 'data/raw/Corporations/Corporations Disclosing/Climate Change/2019_Corporates_Disclosing_to_CDP_Climate_Change.csv',
 'data/raw/Corporations/Corporations Disclosing/Climate Change/2020_Corporates_Disclosing_to_CDP_Climate_Change.csv',
 'data/raw/Corporations/Corporations Disclosing/Water Security/2020_Corporates_Disclosing_to_CDP_Water_Security.csv',
 'data/raw/Corporations/Corporations Disclosing/Water Security/2018_Corporates_Disclosing_to_CDP_Water_Security.csv',
 'data/raw/Corporations/Corporations Disclosing/Water Security/Corporations_Disclosing_to_CDP_Data_Dictionary.csv',
 'data/raw/Corporations/Corporations Disclosing/Water Security/2019_Corporates_Disclosing_to_CDP_Water_Security.csv']

In [16]:
corp_ddict = pd.read_csv('data/raw/Corporations/Corporations Disclosing/Climate Change/Corporations_Disclosing_to_CDP_Data_Dictionary.csv')

corp_ddict

,field,description,column _entries,example
0,account_number,The unique identifier given to every company t...,912,NaN
1,organization,Name of the company disclosing,Archer Daniels Midland,NaN
2,survey_year,Disclosure cycle survey year.,2018,E.g. survey year 2020 ran from March 2020 - Se...
3,country,Country in which the company is incorporated o...,United States of America,NaN
4,region,CDP operating region in which the company is i...,NaN,CDP NA
5,invitation_status,CDP invites companies to disclose to the Inves...,Submitted,NaN
6,public,Companies can submit CDP response in public st...,public,NaN
7,samples,CDP uses Market Cap from major indices and oth...,Water Global,"Continuity, Companies that disclosed the previ..."
8,response_received_date,DateTime company response was first received w...,2018-08-15T00:00:00Z,NaN
9,minimum_tier,Indicates if the highest questionnaire tier a ...,Water - Full,NaN
10,selected_tier,Indicates if the questionnaire tier a company ...,Water - Full,NaN
11,questionnaire,Questionnaire and questionnaire year the compa...,Water Security 2020,NaN
12,theme,Questionnaire Theme the company's response re...,Water,NaN
13,authority_types,Company's can be requested to respond to the C...,"Investor, Supply Chain",NaN
14,activities,CDP Activity Classification System categorizes...,"Aluminium refining, Aluminum, Engines & motor...",CDP Activity Classification System pertains to...
15,sectors,CDP Activity Classification System categorizes...,"Metal products manufacturing, Metal smelting,...",CDP Activity Classification System pertains to...
16,industries,CDP Activity Classification System categorizes...,"Manufacturing, Materials",CDP Activity Classification System pertains to...
17,primary_activity,CDP Activity Classification System categorizes...,Other vehicle equipment & systems,CDP Activity Classification System pertains to...
18,primary_sector,CDP Activity Classification System categorizes...,Powered machinery,CDP Activity Classification System pertains to...
19,primary_industry,CDP Activity Classification System categorizes...,Manufacturing,CDP Activity Classification System pertains to...
20,primary_questionnaire_sector,Describes the sector-specific questionnaire th...,ARNC US,This example pertains to account_number 64106 ...
21,primary_ticker,Financial Market identifier for company,US03965L1008,This example pertains to account_number 64106 ...
22,tickers,Market identifiers (if more than one),NaN,NaN

In [17]:
corp_cl_2018 = pd.read_csv('data/raw/Corporations/Corporations Disclosing/Climate Change/2018_Corporates_Disclosing_to_CDP_Climate_Change.csv')

corp_cl_2018.head()

,account_number,organization,survey_year,country,region,invitation_status,public,samples,response_received_date,minimum_tier,selected_tier,questionnaire,theme,authority_types,activities,sectors,industries,primary_activity,primary_sector,primary_industry,primary_questionnaire_sector,primary_ticker,tickers
0,912,Archer Daniels Midland,2018,United States of America,NaN,Submitted,public,"Agriculture, Benchmark, CCGR1000, CCGR1800, E...",2018-09-04T00:00:00Z,Climate Change - Full,Climate Change - Full,Climate Change 2018,Climate Change,"Investor, Supply Chain","Agricultural products wholesale, Banks, Biofu...","Chemicals, Financial services, Food & beverag...","Food, beverage & agriculture, Materials, Reta...",Oilseed processing,Food & beverage processing,"Food, beverage & agriculture","Food, beverage & tobacco",ADM US,ADM US
1,14683,Pfizer Inc.,2018,United States of America,NaN,Submitted,public,"Benchmark, CCGR1000, CCGR1800, FTSE All-World...",2018-08-15T00:00:00Z,Climate Change - Full,Climate Change - Full,Climate Change 2018,Climate Change,"Investor, Supply Chain",Pharmaceuticals,Biotech & pharma,"Biotech, health care & pharma",Pharmaceuticals,Biotech & pharma,"Biotech, health care & pharma",General,PFE US,PFE US
2,1708,"Berry Global Group, Inc",2018,United States of America,NaN,Submitted,public,"CCGR1000, CCGR1800, Environmental, Plastics &...",2018-08-30T00:00:00Z,Climate Change - Full,Climate Change - Full,Climate Change 2018,Climate Change,"Investor, Supply Chain","Other containers & packaging, Plastic product...","Chemicals, Light manufacturing, Plastic produ...","Manufacturing, Materials",Other containers & packaging,Light manufacturing,Manufacturing,General,BERY US,BERY US
3,17166,SNC-Lavalin Group Inc.,2018,Canada,NaN,Submitted,public,"Benchmark, Canada",2018-09-05T00:00:00Z,Climate Change - Full,Climate Change - Full,Climate Change 2018,Climate Change,"Investor, Supply Chain","Asset managers, Energy infrastructure constru...","Construction, Financial services, Other servi...","Infrastructure, Services",Non-residential building construction,Construction,Infrastructure,General,SNC CN,SNC CN
4,2670,"Canadian Tire Corporation, Limited",2018,Canada,NaN,Submitted,public,NaN,2018-08-15T00:00:00Z,Climate Change - Full,Climate Change - Full,Climate Change 2018,Climate Change,Investor,"Apparel stores, Banks, Specialist retail, Sup...","Convenience retail, Discretionary retail, Fin...","Retail, Services",Specialist retail,Discretionary retail,Retail,General,CTC/A CN,"CTC CN, CTC/A CN"

In [18]:
corp_w_2018 = pd.read_csv('data/raw/Corporations/Corporations Disclosing/Water Security/2018_Corporates_Disclosing_to_CDP_Water_Security.csv')

corp_w_2018.head()

,account_number,organization,survey_year,country,region,invitation_status,public,samples,response_received_date,minimum_tier,selected_tier,questionnaire,theme,authority_types,activities,sectors,industries,primary_activity,primary_sector,primary_industry,primary_questionnaire_sector,primary_ticker,tickers
0,19582,Johnson Controls International PLC,2018,United States of America,NaN,Submitted,public,Water Global,2018-08-29T00:00:00Z,Water - Full,Water - Full,Water 2018,Water,"Investor, Supply Chain","Batteries, Electrical equipment, IT services,...","Electrical & electronic equipment, IT & softw...","Manufacturing, Services",Plastic products,Plastic product manufacturing,Manufacturing,General,JCI US,JCI US
1,9336,International Flavors & Fragrances Inc.,2018,United States of America,NaN,Submitted,public,NaN,2018-08-31T00:00:00Z,Water - Full,Water - Full,Water 2018,Water,"Investor, Supply Chain",Specialty chemicals,Chemicals,Materials,Specialty chemicals,Chemicals,Materials,Chemicals,IFF US,IFF US
2,22901,Bemis Company,2018,United States of America,NaN,Submitted,public,Self selected companies water,2018-08-09T00:00:00Z,Water - Full,Water - Full,Water 2018,Water,"Investor, Supply Chain","Basic plastics, Plastic products","Chemicals, Plastic product manufacturing","Manufacturing, Materials",Plastic products,Plastic product manufacturing,Manufacturing,Chemicals,BMS US,BMS US
3,2407,Bunge,2018,United States of America,NaN,Submitted,public,Water Global,2018-08-29T00:00:00Z,Water - Full,Water - Full,Water 2018,Water,"Investor, Supply Chain","Agricultural products wholesale, Food & bever...","Chemicals, Food & beverage processing, Tradin...","Food, beverage & agriculture, Materials, Retail",Food & beverage wholesale,"Trading, wholesale, distribution, rental & lea...",Retail,Agricultural commodities,BG US,BG US
4,3876,Ingredion Incorporated,2018,United States of America,NaN,Submitted,public,Water Global,2018-08-29T00:00:00Z,Water - Full,Water - Full,Water 2018,Water,"Investor, Supply Chain",Grain & corn milling,Food & beverage processing,"Food, beverage & agriculture",Grain & corn milling,Food & beverage processing,"Food, beverage & agriculture","Food, beverage & tobacco",INGR US,INGR US

In [19]:
corp_w_2018.country.value_counts()

United States of America    192
Canada                       17
Name: country, dtype: int64

# Corporations responses

In [20]:
list_all_files(location='data/', pattern='Corporations Responses')

['data/raw/Corporations/Corporations Responses/Climate Change/2019_Full_Climate_Change_Dataset.csv',
 'data/raw/Corporations/Corporations Responses/Climate Change/2018_Full_Climate_Change_Dataset.csv',
 'data/raw/Corporations/Corporations Responses/Climate Change/2020_Full_Climate_Change_Dataset.csv',
 'data/raw/Corporations/Corporations Responses/Climate Change/Full_Corporations_Response_Data_Dictionary copy.csv',
 'data/raw/Corporations/Corporations Responses/Water Security/2020_Full_Water_Security_Dataset.csv',
 'data/raw/Corporations/Corporations Responses/Water Security/2019_Full_Water_Security_Dataset.csv',
 'data/raw/Corporations/Corporations Responses/Water Security/2018_Full_Water_Security_Dataset.csv',
 'data/raw/Corporations/Corporations Responses/Water Security/Full_Corporations_Response_Data_Dictionary.csv']

In [21]:
corp_cl_2018 = pd.read_csv('data/raw/Corporations/Corporations Responses/Climate Change/2018_Full_Climate_Change_Dataset.csv')

corp_cl_2018.head()

,account_number,organization,survey_year,response_received_date,accounting_period_to,ors_response_id,submission_date,page_name,module_name,question_number,question_unique_reference,column_number,column_name,table_columns_unique_reference,row_number,row_name,data_point_name,data_point_id,response_value,comments
0,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.2,C0. Introduction,C0.2,State the start and end date of the year for w...,3.0,C0.2_C3Indicate if you are providing emissions...,C0.2_c3-Indicate if you are providing emission...,1,Row 1,C0.2_C3_State the start and end date of the ye...,8476,No,NaN
1,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.4,C0. Introduction,C0.4,Select the currency used for all financial inf...,NaN,C0.4,C0.4,0,NaN,C0.4Select the currency used for all financial...,1252,USD,NaN
2,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.2,C0. Introduction,C0.2,State the start and end date of the year for w...,2.0,C0.2_C2End date,C0.2_c2-End date,1,Row 1,C0.2_C2_State the start and end date of the ye...,7523,2017-12-31,NaN
3,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.3,C0. Introduction,C0.3,Select the countries/regions for which you wil...,NaN,C0.3,C0.3,0,NaN,C0.3Select the countries/regions for which you...,1251,Argentina; Barbados; Belize; Bolivia (Plurinat...,NaN
4,912,Archer Daniels Midland,2018,2018-09-04T00:00:00Z,NaN,13370,2018-10-24T16:36:50Z,C0.5,C0. Introduction,C0.5,Select the option that describes the reporting...,NaN,C0.5,C0.5,0,NaN,C0.5Select the option that describes the repor...,163,Operational control,NaN